#!/bin/sh
git clone https://github.com/campl-ucalgary/campl.git
if ! command -v stack &> /dev/null
    then
        echo "Installation failed. Please make sure that you have 'stack' installed"
    else
        stack build
        echo "stack build >>> done"
        mkdir bin
        cp `find . -name mpl-client | grep install` ./bin
        cp `find . -name mpl | grep install` ./bin
        rm -rf campl
        echo "CaMPL was installed Successfully!";
fi