name:                MPLMACH
version:             0.1.0.0
github:              "githubuser/MPLMACH"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/MPLMACH#readme>

dependencies:
- base >= 4.7 && < 5
- optics
- transformers
- bytestring
- mtl
- stm
- pretty
- pretty-show
- async
- network
- pipes
- pipes-attoparsec
- pipes-parse
- attoparsec
- containers
- array
- process

# maybe consider using: to get rid of the liftIO so we can use an MTL representation
# https://hackage.haskell.org/package/exceptions

library:
  source-dirs: src
  # use these for debug dump of the channel manager actions for the machine steps. 
  # cpp-options:
  #   - -DMPL_MACH_DEBUG

executables:
  MPLMACH-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2

    dependencies:
    - MPLMACH

tests:
  MPLMACH-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MPLMACH
    - QuickCheck
    - HUnit
    - hspec
